### ISSUE TITLE
GitHub + Azure - release pipeline

### ISSUE THREAD

**Issue by oskuzz** [oskuzz/React-Family-Dashboard#1]
Build fails when trying to publish project using GitHub release pipelines. Fix this issue.

"github publish error MSB3073: The command "npm run build" exited with code 1."

**Comment by oskuzz** [comment]
The full error:
"There was an error exporting the HTTPS developer certificate to a file.
  failed to load config from /home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/vite.config.ts
  error during build:
EXEC : error : Could not create certificate. [/home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/rfd.client.esproj]
      at file:///home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/vite.config.ts.timestamp-17292837[15](https://github.com/oskuzz/React-Family-Dashboard/actions/runs/11410642512/job/31753355622#step:5:16)941-57a0110156dd1.mjs:24:11
      at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
      at async loadConfigFromBundledFile (file:///home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:66680:15)
      at async loadConfigFromFile (file:///home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:66521:24)
      at async resolveConfig (file:///home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:66129:24)
      at async build (file:///home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65226:[18](https://github.com/oskuzz/React-Family-Dashboard/actions/runs/11410642512/job/31753355622#step:5:19))
      at async CAC.<anonymous> (file:///home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/node_modules/vite/dist/node/cli.js:828:5)
/home/runner/.nuget/packages/microsoft.visualstudio.javascript.sdk/1.0.1184077/Sdk/Sdk.targets(312,5): error MSB3073: The command "npm run build" exited with code 1. [/home/runner/work/React-Family-Dashboard/React-Family-Dashboard/rfd.client/rfd.client.esproj]"

**Comment by oskuzz** [comment]
Switched the client project to a pure next.js project with node.js server. Used a tutorial to set up a GitHub actions flow for deploying node.js projects to Azure. Changed Azure webapp configs to match node.js requirements. Got it to work after a few hours of tinkering with azure login...

**Comment by oskuzz** [comment]
Marking this as closed
